import pathlib


ROOT = pathlib.Path(__file__).resolve().parents[1]
UNICODE_DATA = ROOT / "build" / "UnicodeData.txt"
ARABIC_SHAPING = ROOT / "build" / "ArabicShaping.txt"
OUT = ROOT / "boot" / "src" / "legacy" / "arabic_forms.inc"


def parse_arabic_shaping(path: pathlib.Path) -> dict[int, str]:
    join_type: dict[int, str] = {}
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = [p.strip() for p in line.split(";")]
        if len(parts) < 3:
            continue
        try:
            cp = int(parts[0], 16)
        except ValueError:
            continue
        jt = parts[2]
        if jt:
            join_type[cp] = jt[0]
    return join_type


def parse_presentation_forms(path: pathlib.Path):
    # base_cp -> {tag: low_byte}
    forms: dict[int, dict[str, int]] = {}
    # alef_variant -> {tag: low_byte} for Lam-Alef ligatures
    lamalef: dict[int, dict[str, int]] = {}

    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        # UnicodeData.txt is semicolon separated, 15 fields.
        parts = raw.split(";")
        if len(parts) < 6:
            continue
        try:
            cp = int(parts[0], 16)
        except ValueError:
            continue
        if cp < 0xFE70 or cp > 0xFEFF:
            continue

        decomp = parts[5].strip()
        if not decomp.startswith("<"):
            continue

        toks = decomp.split()
        if not toks:
            continue
        tag = toks[0].strip("<>").lower()
        if tag not in ("isolated", "final", "initial", "medial"):
            continue

        seq: list[int] = []
        ok = True
        for t in toks[1:]:
            try:
                seq.append(int(t, 16))
            except ValueError:
                ok = False
                break
        if not ok or not seq:
            continue

        low = cp & 0xFF

        if len(seq) == 1:
            base = seq[0]
            forms.setdefault(base, {})[tag] = low
        elif len(seq) == 2 and seq[0] == 0x0644:
            variant = seq[1]
            lamalef.setdefault(variant, {})[tag] = low

    return forms, lamalef


def main() -> int:
    if not UNICODE_DATA.exists():
        raise SystemExit(f"Missing {UNICODE_DATA}")
    if not ARABIC_SHAPING.exists():
        raise SystemExit(f"Missing {ARABIC_SHAPING}")

    join_type = parse_arabic_shaping(ARABIC_SHAPING)
    forms, lamalef = parse_presentation_forms(UNICODE_DATA)

    entries = []
    for base in sorted(forms.keys()):
        # Keep to BMP only (fits in 16-bit code unit for our bootloader strings).
        if base > 0xFFFF:
            continue
        f = forms[base]
        iso = f.get("isolated", 0)
        fin = f.get("final", 0)
        ini = f.get("initial", 0)
        med = f.get("medial", 0)
        jt = join_type.get(base, "U")
        entries.append((base, jt, iso, fin, ini, med))

    # Only variants that have both isolated+final forms are useful.
    lamalef_entries = []
    for variant in sorted(lamalef.keys()):
        if variant > 0xFFFF:
            continue
        f = lamalef[variant]
        iso = f.get("isolated", 0)
        fin = f.get("final", 0)
        if iso and fin:
            lamalef_entries.append((variant, iso, fin))

    out_lines = []
    out_lines.append("; ============================================================================")
    out_lines.append("; Auto-generated. DO NOT EDIT BY HAND.")
    out_lines.append(";")
    out_lines.append("; Generated by: tools/gen_arabic_forms.py")
    out_lines.append("; Sources:")
    out_lines.append(f";   - {UNICODE_DATA.as_posix()}")
    out_lines.append(f";   - {ARABIC_SHAPING.as_posix()}")
    out_lines.append(";")
    out_lines.append("; Layout:")
    out_lines.append(";   dw base_cp")
    out_lines.append(";   db join_type, iso_low, fin_low, ini_low, med_low, pad")
    out_lines.append("; ============================================================================")
    out_lines.append("")
    out_lines.append("AR_FORM_ENTRY_SIZE equ 8")
    out_lines.append("")
    out_lines.append("ar_form_table:")
    for base, jt, iso, fin, ini, med in entries:
        out_lines.append(f"    dw 0x{base:04X}")
        out_lines.append(f"    db '{jt}', 0x{iso:02X}, 0x{fin:02X}, 0x{ini:02X}, 0x{med:02X}, 0x00")
    out_lines.append("")
    out_lines.append(f"ar_form_count equ {len(entries)}")
    out_lines.append("")
    out_lines.append("; Lam-Alef ligatures (LAM + Alef variant): dw variant_cp, db iso_low, fin_low")
    out_lines.append("ar_lamalef_table:")
    for variant, iso, fin in lamalef_entries:
        out_lines.append(f"    dw 0x{variant:04X}")
        out_lines.append(f"    db 0x{iso:02X}, 0x{fin:02X}")
    out_lines.append("")
    out_lines.append(f"ar_lamalef_count equ {len(lamalef_entries)}")
    out_lines.append("")

    OUT.write_text("\n".join(out_lines) + "\n", encoding="ascii")
    print(f"Wrote {OUT}")
    print(f"ar_form_count={len(entries)} ar_lamalef_count={len(lamalef_entries)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

