import pathlib


ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "boot" / "src" / "legacy" / "arabic_strings.inc"


def to_u16_dw(s: str) -> list[int]:
    return [ord(ch) for ch in s] + [0]


def fmt_dw(vals: list[int]) -> str:
    return ", ".join(f"0x{v:04X}" for v in vals)


def main() -> int:
    messages: list[tuple[str, str]] = [
        ("msg_ar_title", "نظام بيراميد"),
        ("msg_ar_subtitle", "تسلسل الإقلاع السيادي"),
        ("msg_ar_menu_title", "خيارات الإقلاع"),
        ("msg_ar_menu_1", "١) واجهة رسومية"),
        ("msg_ar_menu_2", "٢) وضع التفاصيل"),
        ("msg_ar_menu_prompt", "اختر ١ أو ٢"),
        ("msg_ar_enter_hint", "اضغط إدخال للتخطي"),
        ("msg_ar_checksum_ver", "فحص سلامة النواة: جاري التحقق"),
        ("msg_ar_checksum_ok", "فحص سلامة النواة: ناجح"),
        ("msg_ar_checksum_fail", "فحص سلامة النواة: فشل"),
        ("msg_ar_checksum_skip", "فحص سلامة النواة: تم التخطي"),
        ("msg_ar_err_disk", "خطأ في قراءة القرص"),
        ("msg_ar_err_hdr", "ترويسة النواة غير صالحة"),
        ("msg_ar_err_a20", "فشل تفعيل الخط ٢٠"),
        ("msg_ar_err_checksum", "فشل فحص سلامة النواة"),
        ("msg_ar_expected", "المتوقع:"),
        ("msg_ar_actual", "الحقيقي:"),
        ("msg_ar_err_code", "رمز:"),
        ("msg_ar_halt", "تم الإيقاف."),
    ]

    out = []
    out.append("; ============================================================================")
    out.append("; Auto-generated. DO NOT EDIT BY HAND.")
    out.append(";")
    out.append("; Generated by: tools/gen_arabic_strings.py")
    out.append("; All strings are stored as UTF-16LE code units (dw) and terminated by 0x0000.")
    out.append("; ============================================================================")
    out.append("")

    for label, text in messages:
        out.append(f"{label}:")
        out.append(f"    dw {fmt_dw(to_u16_dw(text))}")
        out.append("")

    # Countdown template: "الإقلاع التلقائي خلال: 00 ثانية"
    prefix = "الإقلاع التلقائي خلال: "
    suffix = " ثانية"

    out.append("; Countdown line (digits are updated in-place).")
    out.append("ui_countdown_buf:")
    out.append(f"    dw {fmt_dw([ord(ch) for ch in prefix])}")
    out.append("ui_countdown_digit_tens:")
    out.append("    dw 0x0030")
    out.append("ui_countdown_digit_ones:")
    out.append("    dw 0x0030")
    out.append(f"    dw {fmt_dw([ord(ch) for ch in suffix] + [0])}")
    out.append("")

    OUT.write_text("\n".join(out) + "\n", encoding="ascii")
    print(f"Wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

