param(
    [string]$FontPath = "build\\clacon2.ttf",
    [string]$OutPath = "boot\\src\\legacy\\boot_font_8x16.inc",
    [int]$GlyphWidth = 8,
    [int]$GlyphHeight = 16,
    [int]$FontPixelSize = 16
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Add-Type -AssemblyName System.Drawing

function Render-GlyphBytes {
    param(
        [System.Drawing.Font]$Font,
        [int]$CodePoint,
        [int]$W,
        [int]$H
    )

    $bmp = New-Object System.Drawing.Bitmap $W, $H, ([System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.Clear([System.Drawing.Color]::Black)
    $g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::SingleBitPerPixelGridFit
    $g.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::NearestNeighbor
    $g.PixelOffsetMode = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality

    $s = [char]$CodePoint
    $g.DrawString($s, $Font, [System.Drawing.Brushes]::White, 0, 0)

    $bytes = New-Object byte[] $H
    for ($y = 0; $y -lt $H; $y++) {
        $b = 0
        for ($x = 0; $x -lt $W; $x++) {
            $c = $bmp.GetPixel($x, $y)
            if ($c.R -gt 0) {
                $b = $b -bor (1 -shl ($W - 1 - $x))
            }
        }
        $bytes[$y] = [byte]$b
    }

    $g.Dispose()
    $bmp.Dispose()
    return $bytes
}

if (!(Test-Path -LiteralPath $FontPath)) {
    throw "FontPath not found: $FontPath"
}

$pfc = New-Object System.Drawing.Text.PrivateFontCollection
$pfc.AddFontFile($FontPath)
if ($pfc.Families.Count -lt 1) {
    throw "No font families loaded from: $FontPath"
}

$family = $pfc.Families[0]
$font = New-Object System.Drawing.Font $family, $FontPixelSize, ([System.Drawing.FontStyle]::Regular), ([System.Drawing.GraphicsUnit]::Pixel)

$outDir = Split-Path -Parent $OutPath
if ($outDir -and !(Test-Path -LiteralPath $outDir)) {
    New-Item -ItemType Directory -Force -Path $outDir | Out-Null
}

$sb = New-Object System.Text.StringBuilder

[void]$sb.AppendLine("; ============================================================================")
[void]$sb.AppendLine("; Auto-generated. DO NOT EDIT BY HAND.")
[void]$sb.AppendLine(";")
[void]$sb.AppendLine("; Generated by: tools/gen_stage2_font.ps1")
[void]$sb.AppendLine("; Source font:  $FontPath")
[void]$sb.AppendLine("; Cell:         ${GlyphWidth}x${GlyphHeight} (1bpp, MSB left)")
[void]$sb.AppendLine("; Mapping:")
[void]$sb.AppendLine(";   0x20..0x7E = ASCII U+0020..U+007E")
[void]$sb.AppendLine(";   0x10..0x19 = Arabic-Indic digits U+0660..U+0669")
[void]$sb.AppendLine(";   0x70..0xFF = Arabic Presentation Forms-B U+FE70..U+FEFF (low byte index)")
[void]$sb.AppendLine("; ============================================================================")
[void]$sb.AppendLine("")

[void]$sb.AppendLine("boot_font_8x16:")

$missing = @()

for ($idx = 0; $idx -lt 256; $idx++) {
    $cp = $null
    if ($idx -ge 0x20 -and $idx -le 0x7E) {
        $cp = $idx
    } elseif ($idx -ge 0x10 -and $idx -le 0x19) {
        $cp = 0x0660 + ($idx - 0x10)
    } elseif ($idx -ge 0x70 -and $idx -le 0xFF) {
        $cp = 0xFE00 + $idx
    }

    if ($cp -eq $null) {
        $bytes = @(0) * $GlyphHeight
    } else {
        $bytes = Render-GlyphBytes -Font $font -CodePoint $cp -W $GlyphWidth -H $GlyphHeight

        $allZero = $true
        foreach ($b in $bytes) { if ($b -ne 0) { $allZero = $false; break } }
        if ($allZero -and ($idx -ge 0x20 -and $idx -le 0x7E)) { $missing += ("U+{0:X4} (ASCII idx 0x{1:X2})" -f $cp, $idx) }
        if ($allZero -and ($idx -ge 0x70 -and $idx -le 0xFF)) { $missing += ("U+{0:X4} (FE idx 0x{1:X2})" -f $cp, $idx) }
    }

    $hex = ($bytes | ForEach-Object { "0x{0:X2}" -f $_ }) -join ", "
    [void]$sb.AppendLine(("    ; 0x{0:X2}" -f $idx))
    [void]$sb.AppendLine(("    db {0}" -f $hex))
}

$sb.ToString() | Set-Content -LiteralPath $OutPath -Encoding ASCII

Write-Output "Wrote $OutPath"
if ($missing.Count -gt 0) {
    Write-Output "WARNING: Some glyphs rendered as empty (first 25 shown):"
    $missing | Select-Object -First 25 | ForEach-Object { Write-Output ("  - {0}" -f $_) }
    if ($missing.Count -gt 25) {
        Write-Output ("  ... and {0} more" -f ($missing.Count - 25))
    }
}

